version: "3.8"

services:

  postgresql:
    image: docker.io/shawnxxh/bird-interact-postgresql:latest
    container_name: bird_interact_postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123123
      TZ: "Asia/Hong_Kong"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    command:
      - "-c"
      - "max_connections=300"
      - "-c"
      - "shared_buffers=256MB"
    ports:
      - "5432:5432"

  so_eval_env:
    image: docker.io/shawnxxh/bird-interact-agent-so-eval:latest
    container_name: bird_interact_so_eval_env
    volumes:
      - ./:/app/
    depends_on:
      - postgresql
    command: ["tail", "-f", "/dev/null"]


volumes:
  postgresql_data: