version: "3.8"

services:
  postgresql:
    image: docker.io/shawnxxh/bird-interact-postgresql:latest
    container_name: bird_interact_postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123123
      TZ: "Asia/Hong_Kong"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    command:
      - "-c"
      - "max_connections=300"
      - "-c"
      - "shared_buffers=256MB"
    ports:
      - "5432:5432"

  postgresql_full:
    image: docker.io/shawnxxh/bird-interact-postgresql-full:latest
    container_name: bird_interact_postgresql_full
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123123
      TZ: "Asia/Hong_Kong"
    volumes:
      - postgresql_data_full:/var/lib/postgresql/data
    command:
      - "-c"
      - "max_connections=300"
      - "-c"
      - "shared_buffers=256MB"
    ports:
      - "5433:5432"

  bird_interact_eval:
    image: docker.io/shawnxxh/bird-interact-eval:latest
    container_name: bird_interact_eval
    volumes:
      - ../:/app/
    depends_on:
      - postgresql
      - postgresql_full
    command: ["tail", "-f", "/dev/null"]

volumes:
  postgresql_data:
  postgresql_data_full: